server:
  port: 8067

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
          filters:
            - JwtAuthFilter  
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - JwtAuthFilter  
        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - JwtAuthFilter
        - id: station-service
          uri: lb://station-service
          predicates:
            - Path=/api/stations/**
          filters:
            - JwtAuthFilter
        - id: vehicle-battery-service
          uri: lb://vehicle-battery-service
          predicates:
            - Path=/api/vehicles/**
          filters:
            - JwtAuthFilter   
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
          filters:
            - JwtAuthFilter   
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
          filters:
            - JwtAuthFilter       
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/   # <-- dùng tên service container
    registerWithEureka: true
    fetchRegistry: true
